import type { Metadata } from 'next'
import '@/styles/globals.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <div className="layout-wrapper">
          <header>HEADER</header>
          <main>{children}</main>
          <footer>FOOTER</footer>
        </div>
      </body>
    </html>
  )
}
